Repository OpenVoxProject/openvoxdb, pull requests merged in 2025-08, with the labels that each got.

#50 feat: add initial Renovate configuration file
  renovate.json
Labels: github_actions

#51 project.clj: Cleanup perforce leftovers
  project.clj
Labels: skip-changelog

#35 Add JDK21 to CI
  .github/workflows/daily.yml
  .github/workflows/main.yml
  ext/bin/require-leiningen
  ext/test/top-level-cli
  project.clj
  src/puppetlabs/puppetdb/cli/util.clj
  test/puppetlabs/puppetdb/cli/util_test.clj
Labels: enhancement

#24 puppetdb-terminus: migrate to openvoxdb-terminus
  contrib/gem/openvoxdb-terminus.gemspec
Labels: enhancement
